### ISSUE TITLE
How it works for costmap_2d?

### ISSUE THREAD

**Issue by bresnierproject** [mdrwiega/depth_nav_tools#2]
Hey Michal,

Thanks for your code. I'd like to use it for kinect I'm using (V1). Turns out that I'm mapping a 2D plannar indoors environment like most of people does. I want to go forward by using cliff (downstairs) avoidance and hopefully you've already done that. So could you tell me what configuration should I set for my kinect if it's 0.28m height and looking straight ahead? I know kinect's viewing angle has 43 vertical degrees. So, 21.5 degrees upwards and downwards. As my kinect is 0.28m high (and in front of the robot according to navigation tutorials by ROS) it should detect the floor at 0.71084m of distance. 
How costmap_2d perceive the stairs detection? I've sent you an email in case you weren't notified.

Hope you can enlighten me about that

Thanks

**Comment by mdrwiega** [comment]
Hey,

Here ([cliff_detector/config/params.yaml](https://github.com/mdrwiega/depth_nav_tools/blob/kinetic-devel/cliff_detector/config/params.yaml)) is the example configuration of `cliff_detector` package which allows you to detect downstairs.
In your case I think you need to change the following parameters:
- `sensor_mount_height: 0.28`
- `sensor_tilt_angle: 0.0`
-  `range_max: 7.0`

Regarding to costmaps, the node `cliff_detector` detects cliffs/downstairs and send this data to the node `nav_layer_from_points` which creates additional costmap layer which contains this kind of obstacles.
By appropriate configuration of navigation stack you could use this layer in obstacles avoidance module.

There is one issue with the cliff detector because in Kinect it's impossible to differentiate places which are too far for detection and too close. So you need to be aware that some situation may occurs when downstairs won't be detected (especially if stairs are more steep than the lower line of Kinect vertical field of view angle).

To get more detailed information about detection method please look at the following publication:
"[A set of depth sensor processing ROS tools for wheeled mobile robot navigation"(PDF)](http://www.jamris.org/images/ISSUES/ISSUE-2017-02/48_56%20Drwiega.pdf)

Best regards,
Michal

**Comment by bresnierproject** [comment]
Cool, and thanks again for your reply. When I can I will

Regards,

Gerson
