### ISSUE TITLE
Distance to ground calculation

### ISSUE THREAD

**Issue by nakai-omer** [mdrwiega/depth_nav_tools#24]
Hi,

I would be happy to get a little explanation on the following distance to ground calculation:
```cpp
dist_to_ground_[i] = sensor_mount_height_ * sin(M_PI / 2 - delta_row_[i]) /
        cos(M_PI / 2 - delta_row_[i] - alpha);
```

Shouldn't the sin also decrease the alpha? If so, wouldn't it be easier to have:
```cpp
dist_to_ground_[i] = sensor_mount_height_ * tan(M_PI / 2 - delta_row_[i] - alpha);
```

**Comment by mdrwiega** [comment]
I think the original formula is right. Please check the below drawing for the case when $\delta$ is equal to half of FOV.

![kinect_floor](https://user-images.githubusercontent.com/8460945/202564804-bf829059-da6f-43c9-ab27-a6fcdfca9054.png)

Assuming that:
- $sin(\alpha + \gamma ) = \dfrac{d}{l} \rightarrow d = l \cdot sin(\alpha + \gamma )$
- $cos(\gamma) = \dfrac{h}{l} \rightarrow l = \dfrac{h}{cos(\gamma)}$
- $\gamma=\frac{\pi}{2}-\delta$
- $h$ is the `sensor_mount_height`
- $\delta$ depends on the image row - variable `delta_row_[i]`

Then, the threshold value `dist_to_ground` (d) can be calculated as
$$d= l \cdot sin(\alpha + \gamma ) = \dfrac{h}{cos(\gamma)} \cdot sin(\alpha + \gamma ) = h \cdot \dfrac{sin(\pi/2 - \delta + \alpha)}{cos(\pi/2 - \delta)}$$

The sign near $\delta$ was changed in the code because as I remember the sensor I used returned it with a minus.

More details you can find in the following paper: [A set of depth sensor processing ROS tools for wheeled mobile robot navigation](https://www.jamris.org/index.php/JAMRIS/article/view/428/428) .

**Comment by nakai-omer** [comment]
@mdrwiega amazing thank you very much for the detailed answer
